### ISSUE TITLE
[linux] Hat #0 Button 0 is "True" when untouched

### ISSUE THREAD

**Issue by Loader009** [AlexanderDzhoganov/ksp-advanced-flybywire#31]
JoyStick: Microsoft SideWinder Force Feedback 2

As long as the hat is untouched (to no direction pushed), the hat #0 button 0 is always true.
This is an issue because when you set an axis, the button gets into the "combination" and needs to be true so that axis works.

Workaround: give us an option in Controller Configuration to ignore/disable buttons.

**Comment by Gaiiden** [comment]
would like to confirm this and also add it is an issue on Win7 x64 as well using a Saitek X55. If it is possible, rather than outright removing the ability to set buttons/axis together I would also suggest an option to ignore buttons on a *per device* basis. The reason for this is the axis+button assignment is actually useful on my X55 throttle which has a switch for 3 mode settings. So being able to assign the throttle axis when only Mode 1 (button#30) is True is beneficial. But on the joystick I can't use the hat because anything other than its default position will cancel out the axis

**Comment by Eilifein** [comment]
I would also like to confirm that in Win7 x64, KSP x86, v.1.4.6, using a Logitech Extreme 3D Pro, when left untouched AND calibrated several times, during configuration, Hat button left seems always True. When you try to map ANY button, it goes into a combination of the button and Hat#0 Button 0. Also, pushing the button turns True into False.

Thanks in advance, both nlight and ddaf for the great job on this mod!

**Comment by badpandabear** [comment]
I just submitted a pull request for this. The problem was in the SDLController, so Windows users shouldn't see it if they switch to using Xinput. Unless there's another problem I don't know about because I'm a linux user.
